/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mars.gltf 
Author: Mieke Roth (https://sketchfab.com/miekeroth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-2b46962637ee4311af8f0d1d0709fbb2
Title: Mars
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Model = (props) => {
  const { nodes, materials } = useGLTF("/mars.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mercury_1.geometry}
        material={materials.mercurius}
        scale={100}
      />
    </group>
  );
};

useGLTF.preload("/mars.gltf");

export default Model;
